# DigitalOcean App Platform Configuration
# This file helps DigitalOcean understand your app structure

name: speech-skills-ai

# Static Site Configuration
# IMPORTANT: This must be a static_sites component, NOT a web service
static_sites:
  - name: frontend
    github:
      repo: your-username/SppechSkillsAi  # Update with your GitHub username/repo
      branch: master  # or 'main' if that's your default branch
    build_command: npm run build
    output_dir: build
    environment_slug: node-js
    http_port: 8080
    routes:
      - path: /
    # Serve index.html for 404s so /login, /about, etc. work (SPA client-side routing)
    error_document: index.html
    # NO run_command or dockerfile_path - static sites don't need these

# Note: Functions are deployed separately via DigitalOcean Functions
# They don't need to be in this app.yaml file
